arch: "x86_64"

images:
# Try to use release-yyyyMMdd image if available. Note that release-yyyyMMdd will be removed after several months.
- location: "https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-amd64-20231013-1532.qcow2"
  arch: "x86_64"
  digest: "sha512:b2ddc01e8d13dabbcfde6661541aae92219be2d442653950f0e44613ddebaeb80dc7a83e0202c5509c5e72f4bd1f4edee4c83f35191f2562b3f31e20e9e87ec2"
- location: "https://cloud.debian.org/images/cloud/bookworm/20231013-1532/debian-12-generic-arm64-20231013-1532.qcow2"
  arch: "aarch64"
  digest: "sha512:7384741cf214cb789acd84e2c67128a83d1c7995b5b5118190d50cf19a13e3c4169c268ad13e36763d84f8602edd44857cd4597ae1b190f47c8789a8acd97bbc"
# Fallback to the latest release image.
# Hint: run `limactl prune` to invalidate the cache
- location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2"
  arch: "x86_64"
- location: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-arm64.qcow2"
  arch: "aarch64"

# CPUs
# 🟢 Builtin default: min(4, host CPU cores)
cpus: 4

# Memory size
# 🟢 Builtin default: min("4GiB", half of host memory)
memory: "4GiB"

# Disk size
# 🟢 Builtin default: "100GiB"
disk: "100GiB"


mountType: "9p"
mounts:
- location: "~"
  9p:
    msize: "1024KiB"
- location: "~/Works"
  writable: true
  9p:
    msize: "1024KiB"
- location: "/tmp/lima"
  writable: true
  9p:
    msize: "1024KiB"
